# Generated by Django 3.1.2 on 2020-12-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
