# Generated by Django 3.1.2 on 2021-01-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201220_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='create_at',
        ),
    ]
