# Generated by Django 3.1.2 on 2020-10-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('discount', models.IntegerField(blank=True)),
                ('price_sale', models.FloatField()),
                ('type', models.CharField(choices=[('1', 'fruct'), ('2', 'veg'), (None, 'Unknown')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Мужчина'), ('0', 'Женщина')], max_length=1, null=True)),
                ('city', models.CharField(editable=False, max_length=20)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vegefood.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegefood.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
