# Generated by Django 3.1.2 on 2020-11-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('value', models.IntegerField()),
                ('min_coast', models.IntegerField()),
                ('start_at', models.DateTimeField()),
                ('finish_at', models.DateTimeField()),
            ],
        ),
    ]
