# Generated by Django 3.1.2 on 2020-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefood', '0002_auto_20201030_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('1', 'fruit'), ('2', 'veg'), ('3', 'juice'), ('4', 'dried'), (None, 'Unknown')], max_length=20, null=True),
        ),
    ]
