# Generated by Django 3.1.2 on 2020-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefood', '0003_auto_20201112_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
