# Generated by Django 3.1.2 on 2020-11-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefood', '0003_auto_20201030_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
